---
title: "**Syntax I**"
subtitle: "**Tuesday+Friday**"
author: "Quartz Colvin (they/them)"
institute: "Rutgers University"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: ["rutgers", "rutgers-fonts"]
    lib_dir: libs
    includes:
      after_body: [nav.html, header.html]
    nature:
      ratio: "16:9"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false

---

class: center, middle

# So far...

---

# So far, we've studied...

1. **Fundamental concepts in linguistics:** mental grammar, prescriptivism vs. descriptivism, standard vs. non-standard language, grammaticality 

--

2. **Morphology:** the study of the structure of words- morphemes, morphological processes, morphological analysis, hierarchical structure

--

### Now, we're moving on to **syntax!**

**syntax:** the study of the structure of sentences; how sentences are built up out of words

--

First we'll start with something we've already mentioned several times...

- **parts of speech:** nouns, verbs, adjectives, adverbs...

---

class: center, middle

# Parts of speech

---

# Parts of speech 

**Parts of speech** (aka **lexical classes**) are categories we use to classify words

- nouns, verbs, adjectives, adverbs...

--

They were important in the **morphology** unit

- derivational morphology can change a word's *part of speech* 

- inflectional morphology is specific to a *part of speech*: nouns, verbs, and adjectives all inflect differently

--

They will also be important for syntax! 

- sentences are made of words

- a word's *part of speech* determines its role in a sentence

--

  - the subject of a sentence is always a **noun**, every sentence needs a main **verb**...

---

# Parts of speech

What are the parts of speech? 

How do we identify a word's part of speech? 

**Try to define the following:**

.pull-left[

- noun

- verb

- adjective

]

--

.pull-right[

- denotes a person, place, thing

- denotes actions

- adds a description to a noun

]

--

We can provide definitions of these categories

- but, these definitions rely on us **already knowing** the meaning of the word.

  - we know *table* is a noun because we know it refers to a thing

--

- can we figure out a word's part of speech **without knowing what it means?** Just by seeing how it's used in a sentence?

---

class: center, middle

# Exercise (Jabberwocky)

---

# Jabberwocky

.pull-left[

- let's use Lewis Carroll's 1871 poem "Jabberwocky" to figure out another way of considering parts of speech 

- the words are nonsense, but the syntax is still English

- so, we can't rely on what we know about the words, we have to rely on how they're being used!

1. **Guess what the part of speech is for each underlined word**

2. **Be prepared to justify your answer**


]

.pull-right[

***insert jabberwocky image???***
]

---

# Jabberwocky

.pull-left[

There are two main strategies for figuring out a words part of speech based on its usage

- we can consider the word's **syntactic distribution**

- we can consider the words **morphological distribution**

]

.pull-right[

***insert jabberwocky???***

]

---

class: middle, center

# Distribution

---

# Syntactic distribution 

.pull-left[

**Syntactic distribution...**

- Where does the word appear in the sentence?

- What other words appear around it?

Consider the word *borogoves*

- it comes after *the*

- what other words can follow *the*? NOUNS!

- we conclude that *borogoves* is also a noun 

Because it fits the **syntactic distribution** of nouns- it goes where nouns go in the sentence!

]

.pull-right[

***insert jabberwocky???***

]

---

# Morphological distribution

.pull-left[

**Morphological distribution**

- What morphemes does it have? 

- Are they associated with a specific part of speech?

Consider *borogoves* again

- it seems to end in the plural suffix *-s*

- what other words use plural *-s*? NOUNS!

- again, we conclude that *borogoves* is a noun 

Because it fits the **morphological distribution** of nouns- it uses morphemes associated with nouns

]

.pull-right[

***insert jabberwocky???***

]

---

# Part of speech

Parts of speech aren't just random categories you have to memorize in English class

Words of a particular part of speech tend to behave in similar ways:

- They have a similar **morphological distribution** (similar morphemes),

- and a similar **syntactic distribution** (similar role in sentences).

--

That is, they follow a pattern – a pattern that forms part of our mental grammar.

- We pick up these patterns as children acquiring our native language.

- A small child might not know what a noun is, but they might know you can say *take ball, take toy, take teddy, take blankie*... but not **take eat*.

- So categories like noun and verb are part of our mental grammar, even before we learn about them explicitly in an English class.

---

# Parts of speech 

Since these categories are part of our mental grammar, they give us intuitions about how a word can or cannot be used in a sentence.

And we can use these intuitions in a **replacement test** to figure out a word's part of speech:

- Think of a sentence where you know each word's part of speech:

  - *John ate a delicious sandwich.*

- Take a word you don't know and use it to replace one of the words in your sentence.

- If sounds like a well-formed sentence, it probably has the same part of speech!

- If not, move on to the next word and try replacing that instead.

---

# Parts of speech 

Let's go through the following parts of speech one by one:

- noun, verb, adjective, adverb, determiner, preposition, conjunction

--

For each one:

- We'll provide a **definition**

- We'll talk about its **morphological distribution** – what morphemes it can have

- We'll talk about its **syntactic distribution** – where it appears in a sentence

--

Note that these distributions can vary from language to language:

- English: *intelligent student* vs. Spanish: *estudiante inteligente*

--

But in each language, each part of speech has its own morphological and syntactic distribution

---

class: center, middle

# Nouns

---

# Nouns

How can we define a noun?

.pull-left[

- Nouns denote a person, place, or thing...

- but also abstract entities, concepts, and even actions

]

.pull-right[

*student, school, desk*

*hope, idea, year, math, fishing*

]

--

What kinds of nouns are there?

--

We can distinguish between:

.pull-left[

- common nouns

- proper nouns (names)

]

.pull-right[

*girl, river, college*

*Mary, Raritan, Rutgers*

]

---

# Nouns 

**Morphological distribution** - what suffixes can a noun have in English?

.pull-left[

- Nouns can take plural *-s* or possessive *-'s* 

- Derivational morphemes that form nouns: *-tion/-sion, -ness, -ity, -itude, -ing, -ment*...

]

.pull-right[

*cats, dogs, Mary's, students'*

*instruction, happiness, sincerity, ineptitude, reading, encouragement*

]

--

**Syntactic distribution** - where do nouns appear in sentences in English?

.pull-left[

- nouns can follow determiners like *a, the, my*...

- nouns can follow adjectives

- nouns can follow prepositions 

- nouns can be subjects of sentences 

- nouns can be objects of sentences

]

.pull-right[

*a dog, the cat, my friend*

*friendly dog, angry cat, best friend*

*at school, in line, on demand*

*Dogs are humans' best friend*

*I saw a dog*

]

---

# Pronouns 

***continue???*** slide 14 of week 4 slides










---

class: center, middle

# **[FRIDAY SLIDES]** 

---

class: middle, center 

# Constituents!

---

# Constituents 

## What is a constituent? 

- ***A group of words that acts together as a unit***

- a basic structure in syntax

--

Some examples

- **Justin** teaches linguistics.

- **My cat** likes rice.

- **That tall guy from NJ** likes philosophy.

--

Even though the bold constituents can have only one word or several, they act as a unit to describe a single concept.

---

# Constituents: phrases (types)

**Phrases** are types of constituents 

--

Each phrase has a main word (or **head**), and phrases are named after the head word's part of speech.

---

# Constituents: phrases

- Noun phrase (NP)
  
  - *woman, the woman, the happy woman, the woman with the hat*
  
- Prepositional phrase (PP)

  - *into the forest, by the author, for good luck*

- Verb phrase (VP)

  - *eats, eats pizza, eats quickly, eats pizza quickly at midnight*
  
- Adjective phrase (AdjP)

  - *happy*
  
- Adverb phrase (AdvP)

  - *quickly*

**Note that one constituent may contain another, smaller constituent.**

---

class: center, middle

# Constituency tests!

---

# Constituency tests 
We can do tests to determine whether a group of words form a constituent or not.

These are the four tests we'll use:

--

1. replacement/substitution 

2. stand-alone

3. movement 

4. coordination 

**As is usually the case, these tests don't always work 100% of the time, so you should try multiple!!!**

---

# Constituency tests 

Consider the following sentence ([the happy student] and [in New Brunswick] are constituents)

- [The happy student] lives [in New Brunswick]

This is the example sentence which we will perform constituency tests for.

---

# Constituency tests

## Replacement


**Replacement test:** try replacing a group of words with a *pro-form* (a pronoun or another generic expression such as *there, like that, do, do that, that way*).

If it works, or still sounds grammatical, then the words are a constituent.

--

- [The happy student] lives in New Brunswick → [She] lives in New Brunswick
  
  - this works, so [the happy student] is a constituent!

--

- The happy student [lives in New] Brunswick → The happy student [??] Brunswick

  - this **doesn't** work, so [lives in New] is not a constituent 


---

# Constituency tests 

## Stand alone

**Stand alone test:** try coming up with a question that can be answered by just saying the group of words you want to test on its own

- Who lives in New Brunswick? [The happy student]!

  - this works, so [the happy student] is a constituent


---

# Constituency tests  

## Movement 

**Movement test:** try moving a group of words to a different part of the sentence, like the beginning or end of the sentence. You *may* need to add extra words to support this movement.

- The person who lives in New Brunswick is [the happy student].

  - this works, so [the happy student] is a constituent
  
- Student who lives in New Brunswick is [the happy]

  - this doesn't work, so [the happy] is not a constituent


---

# Constituency tests 

## Coordination 

**Coordination test:** coordinating conjunctions like *and* or *or* will always join two words or phrases of the same type. So, if a group of words is a constituent, you should be able to insert another phrase of the same type joined with *and* or *or*

- [The happy student] and [the grumpy professor] live in New Brunswick.

  - this works, so [the happy student] is a constituent


