---
title: "**Morphology II**"
subtitle: "**Tuesday**"
author: "Quartz Colvin (they/them)"
institute: "Rutgers University"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: ["rutgers", "rutgers-fonts"]
    lib_dir: libs
    includes:
      after_body: [nav.html, header.html]
    nature:
      ratio: "16:9"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false

---

class: center, middle

# Recap


---

# Last week...

- So far we've learned what a **morpheme** is.

- And we've learned about different types of morphemes:

  - root vs. affix, free vs. bound, inflectional vs. derivational

--

- Today we're going to learn how to put morphemes together to make new words:

--

  - **Morphological Processes**

--

- But first, I want to clarify a points that can be tricky when breaking down words.

---

# Tricky morphemes

Consider the word *break-able*. Which description best fits this word?

- A compound word with two roots: *break + able*

- A simple word with the root break and the suffix -able

--

We know "able" is a separate word. But do the word *able* and *-able* mean the same thing? Let's put them in sentences so we can use our intuitions.

--

- *Freda studies karate. She is <u>able</u> to break the board.*

- *The board is break<u>-able</u>.*

**What do y'all think?**

--

- The meanings are related, but subtly different.

--

**Generalization:**

- If the meanings are *different*, they're different morphemes.

- So we consider them different morphemes: free root (word) *able*, bound suffix *-able*







---

# Tricky morphemes

We have a similar situation with morphemes like *-less* or *-ful*

--

What does the morpheme in bold mean in each sentence?

--

- *The bucket is* **full** *of water.*

- *A bucket*-**ful** *of water will put out the campfire.*

- *Yuri cared* **less** *than Josephine.*

-  *Yuri was care*-**less** *and made a mistake.*

--

Again, the meanings are **<u>related, but subtly different</u>**, so we consider them different morphemes:

- *able, full,* and *less* are free roots, *-able, -ful,* and *-less* are bound derivational suffixes

--

- If you're stuck on a morpheme, try using it in a sentence – it may clear things up

---

class: center, middle

# Morphological processes

---




# Affixation

Let's move on to morphological processes. The first two should be familiar!

--

- <u>Affixation:</u> Adding an affix: a prefix, suffix, infix, or circumfix.

  - Depending on the type of affix, also called *prefixation, suffixation, infixation, circumfixation.*

--

  - **Prefixation:** *re- + visit → revisit

  - **Suffixation:** *modern + -ize → modernize

  - **Infixation:** Tagalog *bili* 'buy' → *b-um-ili* 'to buy'

  - **Circumfixation:** Indonesian *ajar* 'teach' → *pel-ajar-an* 'subject'

---

# Compounding 

Combining two or more roots into a single word

--

- *tree + house → treehouse*

- *blue + bird → bluebird*

- *health + care → healthcare*

--

Compound words often sound different from the words used
separately – one of the roots will be pronounced with less stress
than if it had been a separate word:

--

- Abraham Lincoln was born in a log cabin – a **tree** house.

- The child played in a **treehouse**.

---

# Compounding

Different languages have different rules for compounding.

--

Germanic languages are well-known for permitting *lots* of compounding:

--

- **German:** *Donaudampfschiffahrtsgesellschaftskapitän*

--

- **Roots:** *Donau- dampf- schiff- fahrts- gesellschafts- kapitän*

--

- **Meaning:** Danube- steam- ship- travel- company- captain

  'captain of the Danube Steamship Company'


---

# Compounding

Fun fact, English is *also* a Germanic language and allows this kind of compounding!

--

We just write these compounds with spaces or hyphens:

- Amazon product title: *Instant Pot Duo 7-in-1 Electric Pressure Cooker*

--

It can be confusing what's a string of words and what's a compound with spaces, but:

- Remember that in a compound, typically not all roots are equally stressed.

  - *My cousin sells* **réal estate**. *Graceland is a* **réal estáte**!

--

- The meaning of compounds is sometimes **non-compositional:** not derived from the words.

--

- ***If it's a long string of nouns, it's probably a compound.***

--

- In the end, spaces are a spelling convention – we don't pronounce them.

---

class: center, middle

# Morphological processes **[NEW!]**




---

# Reduplication 


**Reduplication:** repeating all or part of a morpheme.

--

- Do you like him as a friend or do you *like-like* him?

- My mom always wants to go to a *fancy-shmancy* restaurant.

--

Reduplication is somewhat limited in English, but in some other languages, it's much more **productive** and serves an explicit **grammatical purpose**:

--

.pull-left[

- Indonesian (full reduplication = plural) 

- Tagalog (partial reduplication = future tense)

]


.pull-right[

*orang* "person" → *orang-orang* "people"

*bili* "buy" → *bi-bili* "will buy"

]

---

# Alternation 

**Alternation:** Changing one or more sounds *within the morpheme*

--

- usually most of the sounds stay the same, but one or a few are changed. Alternation can result in *irregular nouns, verbs, etc.*

--

English has many examples! 

--

- Say these words out loud. What is the difference in sound in these words? What is the difference in meaning? Do they involve inflection or derivation?

--

  - goose → geese 

  - ring → rang → rung 

  - Does the baby have **teeth** yet? No, she hasn't started to **teethe**.

  - This tool has no **use**. What?? I **use** it every day...

--

**Allomorphy** is technically a type of alternation, just one in which there is *no difference in meaning*

--

- magical, magician 

---

# Alternation 

It seems inconvenient for speakers... So, why *does* alternation occur? 

--

Because some sound changes only occur in certain contexts. For example:

--

- [t] commonly becomes [ʃ] (sh) before y sounds – a change called *palatalization*

--

  - Examples: *edit > edition, Egypt > Egyptian, minute > minutiae*

--

- But this change doesn't tend to happen at the end of the word or before vowels like [a], [o]

--

  - Example: *edit, editing, editor, Egypt, minute* all keep their [t] sound

--

End result? Morpheme comes to be pronounced differently in different contexts, which we saw a bit from our morphological analysis class last week!

--

**Alternation IS convenient (in a way)! In terms of sound and pronunciation!**


---

# Suppletion 

**Suppletion:** When an inflected form is phonetically very different from other forms of the same word. The result is even more highly irregular.

.pull-left[

- Regular past tense:

- **Suppletive past tense:**

- Regular adjective comparison: 

- **Suppletive adjective comparison:**

]

.pull-right[

*walk, walked, jump, jumped*

*is, was, go, went*

*nice, nicer, nicest, big bigger, biggest*

*good, better, best, bad, worse, worst*


]

---

# Suppletion 

Often occurs when words of different origins are reinterpreted as forms of the same word

.pull-left[

What forms does **to be** take?

- I __ happy

- You __ happy 

- She __ happy

- Yesterday I __ happy

- Yesterday they __ happy

- I have __ happy for a while

- I like __ happy :)

]

--

.pull-right[

A lot of these forms have different origins (apparently! I did not know this)

- *am, is, are* → verb meaning **to be**

- *be, been, being* → verb meaning **to become**

- *was, were* → verb meaning **to stay**

]

--

Over time, these different verbs became interpreted as different forms of **to be**... leading to **to be** having very different forms, i.e. **suppletion**!

---

# Suppletion (not in English!)

In a given language, suppletion doesn't usually affect a lot of words, but the words it *does* affect tend to be **very frequent**, like *to be, to go, to have, to give, good, bad...*

--


.pull-left[
<u>**Spanish** *ir* "to go"</u> 

voy "i go" → vas "you go" → va "s/he goes"  

fui "i went" → fuiste "you went" → fue "s/he went" 

iré "i will go" → irás "you will go" → irá "s/he will go"

<u>**Danish** *lille "little, small"</u>

singular *lille* → *et lille hus* "a little house" 

plural *små* → *to små huse* "two little houses"

]

.pull-right[
Latin *ire* "to go, to move"

Latin *vadere* "to go, to walk* 

Latin *esse* "to be"

Latin *ire* "to go, to move"

.

(compare English *little*)

(compare English *small*)

]


---

# Zero derivation 

So far we've seen that we can use **derivational morphemes** to change a words part of speech 

--

- *magnet* (noun) → *magnet-ize* (verb) 

- *atom* (noun) → *atom-ic* (adjective)

--

BUT in English, for example, we can sometimes change a word's part of speech without adding anything!

--

.pull-left[
- I'm going to *jump* (V) over that railing.

- Please *email* (N) me about that later.

]

.pull-right[

- That was a nice *jump* (N)!

- I *emailed* (V) you yesterday.

]

--

**Spanish**

- *un post* (a social media post) → *postear* (to post on social media)

--

**Zero derivation:** deriving a new word without adding anything

- not all languages do this, but English allows it a lot :)

---

# Acronyms

**Acronym:** a word formed from the initials of other words

--

- NASA → National Air and Space Administration 

--

If each letter is pronounced *separately*, it's called **initialism**

--

- FBI, CIA

--

Acronyms are a fairly recent thing, since the 20th century (from military, government, tech, and corporate terms), so it's not super common 

Some more examples...

--

- *laser* → Light Amplification by Stimulated Emission of Radiation 

- *scuba* → Self Contained Underwater Breathing Apparatus

---

# Blends 

Another more recent way of making words is **blend** (aka **portmanteau**): taking parts of words that are not morphemes and combining them

--

- *smog* = smoke + fog 

- *brunch* = breakfast + lunch

--

Most English words are not blends, so **beware of folk etymologies!**

--

- **etymology:** study of the origins of words 

--

- **folk etymology:** *false claims* about the origins of a word

--

*Oxford English Dictionary, Etymonline,* and even *Wiktionary* are great sources about the origins of words. And remember that certain morphological processes are more common than others.

---

# Clipping

**Clipping:** making new morphemes by shortening ("clipping") an existing word

--

- *advertisement → ad*

- *laboratory → lab*

- *veterinarian → vet*

--

Clipping isn't part of the morphology of the original word! It's a new creation! 

--

- *laboratory*'s root is *labor*, NOT *lab*

--

But, we can use this new root morpheme to make new words (clipped compounds)

- *lab-coat, ad-break*

---

# Reanalysis

What morphemes do the following words have? What does each morpheme mean?

--

- *algebra*

- *hamburger*

- *invent, prevent, event*

--

**Reanalysis** or **rebracketing** is when morpheme boundaries are *reinterpreted* over time

--

- *a napron → an apron* (this one blows my mind)

--

Morpheme boundaries can be **lost**...

- *al-jabr* (Arabic) → *algebra* (English)

--

Morpheme boundaries can be **moved**...

- *Hamburg-er* (German) "person/thing from Hamburg" → *ham-burger* (English)

---

# Reanalysis

Morpheme boundaries can become ambiguous 

--

- Latin *in-* 'in' + *venire* 'to come'

- Latin *pre-* 'before' + *venire* 

- Latin *ex-* 'out' + *venire*

→ English *invent, prevent, event*

---

# Reanalysis (how??)

How does reanalysis happen?

--

As kids, we form our mental grammar by **listening** to our caregivers and **deducing the rules** that account for the things they say

--

But sometimes the rules we deduce are different from the rules they're actually using... this is one reason why language changes over time!

--

In the case of morphology, this can result in **reanalysis**

--

- **Generation 1:**  [əneɪ̯ prən] =* "a napron*"

- **Generation 2:** hears this sound sequence, and interprets it as *"an apron"*

  - Generation 2's grammar has changed and they can generalize the new *"apron"* word to other contexts, such as *the apron, two aprons*
  

---

class: middle, center

# Multiple morphological processes


---

# Multiple processes

Morphological processes:

- affixation, compounding, reduplication, alternation, suppletion

--

As we saw in the non-English datasets last week, it's also possible for words to exhibit *multiple* morphological processes

--

- *break* → *broken* (alternation)

- *break* → *brok-en* (alternation + suffixing)

---

class: middle, center

# Practice!

### Identifying word-formation processes 

---

# Identifying word-formation processes

- Identify the morphological processes involved in the following words. 

- Some will exhibit one process, some will exhibit multiple. 

*(Note: Say the words out loud to hear differences in sound.)*

***word pairs are on the next slide!***

---

# Identifying word-formation processes

1. feed → fed

2. leaf →  leaves

3. peace →  peaceful

4. foot, ball → football 

5. good →  best

6. chair, woman →  chairwomen

7. back, pack →  backpacks

8. like →  like-liked

9. go →  underwent

---

class: center, middle

# Etymology

---

# Note on etymology

Processes like **reanalysis** is also why we can't fully rely on etymology (the origin of words) to explain words today:

--

- They don't always mean or have the same morphemes as their original sources.

--

Generally speaking (unless we're specifically studying language change),

- We should try to analyze language **synchronically:** as it is spoken at one moment in time

- Rather than **diachronically:** as it has changed over time

--

- And this makes sense!! – you don't have to know a language's history to speak it fluently!

---

# Key takeaways 

We have many different ways of using morphology to build new words!

- affixation, compounding, reduplication, alternation, suppletion, reanalysis, zero-derivation

--

We've also seen the rise of new word-formation processes in the past century:

- acronyms, blends, clippings

--

- Remember these three are newer word-formation processes, so take it with a grain of salt when someone tries to tell you a word derives from an acronym or blend.

- ...It might be a false etymology

---

# Coming up 

***Only one more morphology class! Then we move on to Syntax!***

### Reading 

- **Sections 4.3, 4.4 and 4.5** from *Language Files* if you haven't already

### Homework

- **HW1 will be due Feb 8**

### Reminders

- my office hour is in person and on Zoom, Mondays 2-3pm!

  - in-person in Room 3 in the Linguistics Department basement

  - the Zoom link is on Canvas






